source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

#target 'MHBlurTutorials_Example', :exclusive => true do
#  pod "MHBlurTutorials", :path => "/Users/Ptitematil2/MHBlurTutorials/MHBlurTutorials.podspec"
#end

pod 'MHBlurTutorials', :git => 'https://github.com/Ptitematil2/MHBlurTutorials.git'