source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MHBlurTutorials_Example', :exclusive => true do
  pod "MHBlurTutorials", :path => "../"
end

target 'MHBlurTutorials_Tests', :exclusive => true do
  pod "MHBlurTutorials", :path => "../"

  pod 'FBSnapshotTestCase'
end
